{% set name = "tblis" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/devinamatthews/tblis/archive/4de1919.tar.gz
  sha256: 85b72884022edd2612e3a0b3ed12aa6237d3989b581091d21f58124a7450aaeb

build:
  skip: true  # [win]
  number: 0
  run_exports:
    - {{ pin_subpackage(name, min_pin='x.x', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - make
    - sed
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - libhwloc

test:
  commands:
    - ls -l $PREFIX/lib                                    # [unix]
    - test -L $PREFIX/lib/libtblis${SHLIB_EXT}             # [unix]
    - test ! -f $PREFIX/lib/libtblis.a                     # [unix]
    - test -L $PREFIX/lib/libtci${SHLIB_EXT}               # [unix]
    - test ! -f $PREFIX/lib/libtci.a                       # [unix]
    - test -f $PREFIX/include/tblis/tblis.h                # [unix]
    - test -f $PREFIX/include/tci.h                        # [unix]
    - ldd -v $PREFIX/lib/libtblis${SHLIB_EXT}              # [linux]
    - ldd -v $PREFIX/lib/libtci${SHLIB_EXT}                # [linux]
    - otool -L $PREFIX/lib/libtblis${SHLIB_EXT}            # [osx]
    - otool -L $PREFIX/lib/libtci${SHLIB_EXT}              # [osx]

about:
  home: https://github.com/devinamatthews/tblis
  summary: 'Tensor-Based Library Instantiation Software'
  description: |
    TBLIS is a library and framework for performing tensor operations,
    especially tensor contraction, using native algorithms. In this context,
    native means that TBLIS does not translate tensor operations into matrix
    operations using the BLAS libraries. Instead, TBLIS uses the philosophy
    (and certain low-level kernels) of the BLIS framework to implement tensor
    contraction with essentially zero overhead compared to matrix
    multiplication. TBLIS also aims to offer a convenient C++ interface for
    tensors and tensor operations, as well as a stable C interface with high
    portability.
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - src/external/catch/LICENSE.txt
    - src/external/marray/LICENSE
    - src/external/stl_ext/LICENSE
    - src/external/tci/LICENSE
  doc_url: https://github.com/devinamatthews/tblis/wiki
  dev_url: https://github.com/devinamatthews/tblis

extra:
  recipe-maintainers:
    - chillenb
